services:

  - type: web

    name: travel-extractor

    env: python

    plan: free

    buildCommand: "pip install --no-cache-dir -r requirements.txt"

    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker app:app --bind=0.0.0.0:$PORT"

    autoDeploy: true

    envVars:

      - key: PYTHONUNBUFFERED

        value: "1"

      - key: PORT

        value: "8000"

 